"""message

Revision ID: f18efdb78526
Revises: e8d3a629aab2
Create Date: 2026-02-23 00:26:21.229193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18efdb78526'
down_revision = 'e8d3a629aab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
